# Generated by Django 2.2.4 on 2020-08-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='text',
            field=models.TextField(default='Текст жалобы', max_length=500, verbose_name='Текст жалобы'),
        ),
    ]
