# Generated by Django 2.2.4 on 2020-08-20 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20200820_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owner_phone_pure',
            new_name='phone_pure',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owners_phonenumber',
            new_name='phonenumber',
        ),
    ]
