# Generated by Django 2.2.4 on 2020-08-20 16:05

from django.db import migrations


def add_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        Owner.objects.get_or_create(name=flat.owner, phonenumber=flat.owners_phonenumber, phone_pure=flat.owner_phone_pure)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20200820_1921'),
    ]

    operations = [
        migrations.RunPython(add_owners)
    ]
