# Generated by Django 2.2.4 on 2020-08-20 16:05

from django.db import migrations


def add_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        owner = Owner.objects.get(phonenumber=flat.owners_phonenumber)
        owner.flat.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20200820_1944'),
    ]

    operations = [
        migrations.RunPython(add_flats)
    ]
