# Generated by Django 2.2.4 on 2020-08-24 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20200821_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='flat',
            field=models.ForeignKey(
                default=None, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='complaint', to='property.Flat',
                verbose_name='На какую квартиру пожаловались'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(
                default=None, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='complainer', to=settings.AUTH_USER_MODEL,
                verbose_name='Кто жаловался'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='flat',
            field=models.ManyToManyField(
                db_index=True, related_name='owners',
                to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
